"""add users table with age column

Revision ID: f0ccee9b49fe
Revises: 
Create Date: 2026-05-19 16:43:36.059248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f0ccee9b49fe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_id', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=True))
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('admin', 'user', name='user_role'),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.alter_column('users', 'role',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('admin', 'user', name='user_role'),
               existing_nullable=False)
    op.drop_column('users', 'age')
    op.drop_column('users', 'user_id')
    # ### end Alembic commands ###
