from typing import Any, Protocol

import pandas as pd


class TitanicQueryPort(Protocol):
    def get_titanic_data(self) -> pd.DataFrame: ...

    def get_titanic_data_count(self) -> int: ...

    def get_titanic_data_count_survived(self) -> int: ...

    def get_titanic_data_count_dead(self) -> int: ...

    def has_decision_tree_model(self) -> bool: ...

    def get_model_name_and_accuracy(self) -> dict[str, Any]: ...
